<div class="level-<?php echo $this->getLevel() ?> dropdown">
    <div class="col">
        <h2 class="title"><?php echo $this->__('Static text example:') ?></h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt placerat eros et dapibus. Nunc urna ipsum, auctor id cursus id, semper at nunc. Morbi facilisis dolor sit amet velit posuere in tincidunt tellus iaculis.</p>
    </div>
</div>
