<?php /* @var $this RonisBT_TopMenu_Block_Navigation */ ?>
<?php $_afHelper = Mage::helper('adminforms/image'); ?>
<?php $_menu = $this->getMenuItems() ?>

<?php if (!empty($_menu)): ?>
<div class="nav-container">
    <div class="burger-menu-btn mobile mobile-only" title="<?php echo $this->__('Show Menu') ?>"></div>
    <div class="burger-menu mobile mobile-only no-display">
        <div class="mobile-navigation mobile-only">
            <ul>
                <li class="level0">
                    <?php echo $this->__('Shop By Brand') ?>
                    <?php foreach ($_menu as $_item): ?>
                        <?php echo $this->drawItem($_item, 1, false)//, $customTitle) ?>
                    <?php endforeach ?>
                    <ul>

                        <li class="level1"><a href="<?php echo Mage::getUrl('evisu') ?>"><?php echo $this->__('Evisu') ?></a></li>
                        <li class="level1"><a href="<?php echo Mage::getUrl('evisu-genes') ?>"><?php echo $this->__('Evisu Genes') ?></a></li>
                        <li class="level1"><a href="<?php echo Mage::getUrl('evergreen') ?>"><?php echo $this->__('Evergreen') ?></a></li>
                        <li class="level1"><a href="<?php echo Mage::getUrl('private-stock') ?>"><?php echo $this->__('Private Stock') ?></a></li>
                    </ul>
                </li>
                <li class="level0">
                    <?php echo $this->__('Shop By Product') ?>
                    <ul>
                        <li class="level1"><a href="/private-collection/category-1/masami-vintage-zip-hoody-indigo.html"><?php echo $this->__('Tops') ?></a></li>
                        <li class="level1"><a href="<?php echo Mage::getUrl('bottoms') ?>"><?php echo $this->__('Bottoms') ?></a></li>
                        <li class="level1"><a href="<?php echo Mage::getUrl('accessories') ?>"><?php echo $this->__('Accessories') ?></a></li>
                        <li class="level1"><a href="<?php echo Mage::getUrl('women') ?>"><?php echo $this->__('Women') ?></a></li>
                    </ul>
                </li>
                <li class="level0">
                    <a href="<?php echo Mage::getUrl('lookbook') ?>"><?php echo $this->__('Lookbook') ?></a>
                </li>
                <li class="level0">
                    <a href="<?php echo Mage::getUrl('blog') ?>"><?php echo $this->__('Blog') ?></a>
                </li>
                <li class="level0">
                    <a href="<?php echo Mage::getUrl('evisu-rules') ?>"><?php echo $this->__('Evisu Rules') ?></a>
                </li>
                <li class="level0">
                    <a href="<?php echo Mage::getUrl('contacts') ?>"><?php echo $this->__('Contact Us') ?></a>
                </li>
                <li class="level0">
                    <a href="<?php echo Mage::getUrl('customer/account') ?>"><?php echo $this->__('My Account') ?></a>
                </li>
            </ul>
            <div class="additional-menu">
                <ul>
                    <li class="about-us">
                        <a href="<?php echo Mage::getUrl('about-us') ?>"><?php echo $this->__('About Us') ?></a>
                    </li><li class="store-locator">
                        <a href="<?php echo Mage::getUrl('store-locator') ?>"><?php echo $this->__('Store Locator') ?></a>
                    </li><li class="fit-guide">
                        <a href="<?php echo Mage::getUrl('fit-guide') ?>"><?php echo $this->__('Fit Guide') ?></a>
                    </li>
                </ul>
            </div>
            <?php echo $this->getChildHtml('currency_mobile') ?>
            <div class="mobile-store-switcher">
                <div class="caption"><?php echo $this->__('Store') ?></div>
                <?php $countries = array('1' => array('value' => 'GB', 'label' => 'UK'), '2' => array('value' => 'US', 'label' => 'US'), '3' => array('value' => 'HK', 'label' => 'AP')); ?>
                <ul>
                    <?php foreach ($countries as $store => $country): ?>
                        <li class="store-switch-item<?php if(Mage::app()->getStore()->getWebsiteId() == $store): ?> active<?php endIf; ?>" data-value="<?php echo $country['value'] ?>">
                            <span><?php echo $country['label'] ?></span>
                        </li>
                    <?php endforeach; ?>
                </ul>
                <script type="text/javascript">
                    jQuery('.store-switch-item').on('click', function(){
                        countryCode = jQuery(this).data('value');
                        onChangeUrl = '<?php echo Mage::helper('storeswitcher')->getCountryUrl(); ?>';
                        url = onChangeUrl.replace('%geoip_code%', countryCode);
                        setLocation(url);
                    });
                </script>
            </div>
        </div>
    </div>
    <ul id="nav" class="no-mobile">
        <li class="level0 nav-1 nav-shop top-level">
            <a class="main-menu-item" href="javascript:void(0)" title="<?php echo $this->__('Shop'); ?>">
                <?php echo $this->__('Shop'); ?>
            </a>
            <?php if ($_menu): ?>
                <div class="shop-menu-container no-display">
                    <ul class="level0">
                        <?php /*
                        <li class="category-image-holder">
                            <div class="image-holder">
                                <?php $defaultMenuImage = $_afHelper->init('catalog/category', Mage::helper('topmenu')->getDefaultCategoryImage(), '')->resize(487, 443); ?>
                                <img width="487" height="443" id="menu-category-image" src="<?php echo $defaultMenuImage ?>" rel="<?php echo $defaultMenuImage ?>" alt="menu-category-image" />
                            </div>
                        </li> */ ?>
                        <?php foreach ($_menu as $_item): ?>
                            <?php $menuThumbnailImage = ''; //$_item->getCategory()->getMenuThumbnailImage() ?>
                            <?php $customTitle = ($menuThumbnailImage) ? '<img width="67", height="29" src="' . $_afHelper->init('catalog/category/', $menuThumbnailImage, '')->resize(67, 29) . '" alt="" />' : false ; ?>
                            <?php echo $this->drawItem($_item, 1, false)//, $customTitle) ?>
                        <?php endforeach ?>
                    </ul>
                </div>
            <?php endif; ?>
        </li>
        <?php if($cmsMenuItems = Mage::helper('topmenu')->getCmsMenuItems()): ?>
            <?php foreach ($cmsMenuItems as $cmsMenuItem): ?>
                <li class="level0 top-level">
                    <a href="<?php echo $cmsMenuItem->getUrl() ?>">
                        <span><?php echo $cmsMenuItem->getName() ?></span>
                    </a>
                </li>
            <?php endForeach; ?>
        <?php endIf; ?>
        <?php /*
            <li class="level0 top-level">
                <a href="<?php echo Mage::getUrl('blog'); ?>">
                    <span><?php echo $this->__('Blog'); ?></span>
                </a>
            </li>
        */ ?>
    </ul>
</div>
<?php endif; ?>
