<?php /* @var $this RonisBT_TopMenu_Block_Navigation */ ?>
<?php $_afHelper = Mage::helper('adminforms/image'); ?>
<?php $_menu = $this->getMenuItems() ?>

<?php if (!empty($_menu)): ?>
<div class="nav-container">
    <ul id="nav">
        <li class="level0 nav-1 nav-shop top-level">
            <a class="main-menu-item" href="javascript:void(0)" title="<?php echo $this->__('Shop'); ?>">
                <?php echo $this->__('Shop'); ?>
            </a>
            <?php if ($_menu): ?>
                <ul class="level0 no-display">
                    <li class="category-image-holder">
                        <div class="image-holder">
                            <?php $defaultMenuImage = $_afHelper->init('catalog/category', Mage::helper('topmenu')->getDefaultCategoryImage(), '')->resize(487, 443); ?>
                            <img width="487" height="443" id="menu-category-image" src="<?php echo $defaultMenuImage ?>" rel="<?php echo $defaultMenuImage ?>" alt="menu-category-image" />
                        </div>
                    </li>
                    <?php foreach ($_menu as $_item): ?>
                        <?php $menuThumbnailImage = $_item->getCategory()->getMenuThumbnailImage() ?>
                        <?php $customTitle = ($menuThumbnailImage) ? '<img width="67", height="29" src="' . $_afHelper->init('catalog/category/', $menuThumbnailImage, '')->resize(67, 29) . '" alt="" />' : false ; ?>
                        <?php echo $this->drawItem($_item, 1, false)//, $customTitle) ?>
                    <?php endforeach ?>
                </ul>
            <?php endif; ?>
        </li>
        <?php /*
        <li class="level0 top-level">
            <a href="<?php echo Mage::getUrl('lookbook'); ?>">
                <span><?php echo $this->__('Lookbook'); ?></span>
            </a>
        </li>

        <li class="level0 top-level">
            <a href="<?php echo Mage::getUrl('heritage'); ?>">
                <span><?php echo $this->__('Heritage'); ?></span>
            </a>
        </li>
        <li class="level0 top-level">
            <a href="<?php echo Mage::getUrl('blog'); ?>">
                <span><?php echo $this->__('Blog'); ?></span>
            </a>
        </li>
        <li class="level0 top-level">
            <a href="<?php echo Mage::getUrl('press'); ?>">
                <span><?php echo $this->__('Press'); ?></span>
            </a>
        </li>
        */ ?>

        <?php if($cmsMenuItems = Mage::helper('topmenu')->getCmsMenuItems()): ?>
            <?php foreach ($cmsMenuItems as $cmsMenuItem): ?>
                <li class="level0 top-level">
                    <a href="<?php echo $cmsMenuItem->getUrl() ?>">
                        <span><?php echo $cmsMenuItem->getName() ?></span>
                    </a>
                </li>
            <?php endForeach; ?>
        <?php endIf; ?>
    </ul>
    <span class="search-btn"></span>
</div>
<?php endif; ?>
