<?php /* @var $this Mage_ProductAlert_Block_Product_View */ ?>

<?php $_product = Mage::registry('current_product') ?>
<script>
    AlertOOS.productId = '<?php echo $_product->getId() ?>';
    AlertOOS.sku = '<?php echo $_product->getSku() ?>';
    jQuery('.alertoos-btn').on('click', function(){
        var c = '<div class="box-modal">' +
            '<div class="box-modal_close arcticmodal-close">X</div>' +
                '<div id="alertoos-result">' +
                    '<form id="alertoos-form" action="<?php echo Mage::getUrl('alertoos/alert/post') ?>" method="post">' +
                        '<input type="hidden" name="product_id" value="'+ AlertOOS.productId +'" />' +
                        '<input type="hidden" name="sku" value="' + AlertOOS.sku + '" />' +
                        '<div class="header-first"><?php echo $this->__('Email Me') ?></div>' +
                        '<div class="header-second"><?php echo $this->__('When back in stock') ?></div>' +
                        '<div><span class="name">' + <?php echo json_encode($_product->getName()) ?> + '</span><?php if($_product->getSecondName()): ?> - <span class="second-name">' + <?php echo json_encode($_product->getSecondName()) ?> + '</span><?php endIf; ?></div>' +
                        '<div class="form-fields">' +
                            '<div class="form-field"><input value="<?php echo Mage::helper('evisu_alertoos')->getUserFirstName() ?>" class="input-text required-entry" name="first_name" type="text" placeholder="<?php echo $this->__('First Name') ?>"/></div>' +
                            '<div class="form-field"><input value="<?php echo Mage::helper('evisu_alertoos')->getUserLastName() ?>" class="input-text required-entry" name="last_name" type="text" placeholder="<?php echo $this->__('Last Name') ?>"/></div>' +
                            '<div class="form-field"><input value="<?php echo Mage::helper('evisu_alertoos')->getUserEmail() ?>" class="input-text required-entry validate-email" name="email_address" type="text" placeholder="<?php echo $this->__('Email Address') ?>"/></div>' +
                            '<div class="form-field"><input value="" class="input-text" name="telephone" type="text" placeholder="<?php echo $this->__('Telephone') ?>"/></div>' +
                        '</div>' +
                        '<div class="form-btn"><input type="submit" value="<?php echo $this->__('Submit') ?>"/></div>' +
                    '</form>' +
                '</div>' +
            '</div>';
        jQuery.arcticmodal({
            content: c,
            afterOpen: function(data, el) {
                AlertOOS.init();
            }
        });
    });
</script>
