<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>

<?php if( $this->isExpanded() ): ?>
    <div class="block-subtitle"><?php echo $this->__('filter by') ?></div>
    <div class="sort-by-title no-mobile"><?php echo $this->__('sort by') ?></div>
    <div class="sort-by-holder no-mobile">
        <div class="sort-by">
            <ul>
                <?php $orderSortedArray = array('position' => null, 'price' => null, 'name' => null) ?>
                <?php foreach($this->getAvailableOrders() as $_key => $_order): ?>
                    <?php $orderSortedArray[$_key] = $_order ?>
                <?php endForeach; ?>

                <?php foreach($orderSortedArray as $_key => $_order): ?>
                    <?php if($_key == 'price'): ?>
                        <li>
                            <span class="custom-checkbox<?php if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'asc'): ?> checked<?php endif; ?>" onclick="setLocation('<?php echo $this->getOrderUrl($_key, 'asc') ?>')">
                                <?php echo $this->__('price low-high') ?>
                            </span>
                        </li>
                        <li>
                            <span class="custom-checkbox<?php if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'desc'): ?> checked<?php endif; ?>" onclick="setLocation('<?php echo $this->getOrderUrl($_key, 'desc') ?>')">
                                <?php echo $this->__('price high-low') ?>
                            </span>
                        </li>
                    <?php endIf; ?>
                    <?php if($_key == 'name'): ?>
                        <li>
                            <span class="custom-checkbox<?php if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'asc'): ?> checked<?php endif; ?>" onclick="setLocation('<?php echo $this->getOrderUrl($_key, 'asc') ?>')">
                                <?php echo $this->__('name') ?>
                            </span>
                        </li>
                    <?php endIf; ?>
                    <?php if($_key == 'position'): ?>
                        <li>
                            <span class="custom-checkbox<?php if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'asc'): ?> checked<?php endif; ?>" onclick="setLocation('<?php echo $this->getOrderUrl($_key, 'asc') ?>')">
                                <?php echo $this->__('position') ?>
                            </span>
                        </li>
                    <?php endIf; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>

<?php /*
<div class="pager">
    <p class="amount">
        <?php if($this->getLastPageNum()>1): ?>
            <?php echo $this->__('Items %s-%s of %s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
        <?php else: ?>
            <?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?>
        <?php endif; ?>
    </p>

    <div class="limiter">
        <label><?php echo $this->__('Show') ?></label>
        <select onchange="setLocation(this.value)">
        <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
            <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                <?php echo $_limit ?>
            </option>
        <?php endforeach; ?>
        </select> <?php echo $this->__('per page') ?>
    </div>

    <?php echo $this->getPagerHtml() ?>

</div>
*/ ?>
