<?php /* @var $this Mage_Catalog_Block_Product_List_Toolbar */ ?>

<?php if($this->isExpanded() && $this->isEnabledViewSwitcher()): ?>
    <p class="list-view-mode">
        <?php $_modes = $this->getModes() ?>
        <?php if($_modes && count($_modes) > 1): ?>
            <label><?php echo $this->__('View') ?>:</label>
            <?php $_i=1; $_fix=''; foreach ($this->getModes() as $_code=>$_label): ?>
                <?php if ($_i==1 && strtolower($_code)=='list') $_fix='-fix'; ?>
                <?php if($this->isModeActive($_code)): ?>
                    <strong class="active <?php echo strtolower($_code); echo $_fix; ?>" title="<?php echo $_label ?>"><?php echo $_label ?></strong>
                <?php else: ?>
                    <a class="<?php echo strtolower($_code); echo $_fix; ?>" title="<?php echo $_label ?>" href="<?php echo $this->getModeUrl($_code) ?>"><?php echo $_label ?></a>
                <?php endif; ?>
                <?php $_i++; endforeach; ?>
        <?php endif; ?>
    </p>
<?php endif ?>
