<?php /* @var $this Mage_Customer_Block_Form_Login */ ?>

<div class="page-title">
    <div class="image-holder">
        <img width="1009" height="1233" src="<?php echo $this->getSkinUrl('images/myaccount/login.jpg') ?>" alt="" />
    </div>
    <h1><?php echo $this->__('My Account') ?></h1>
</div>
<div class="breadcrumbs">
    <ul>
        <li class="home">
            <a title="<?php echo $this->__('Go to Home Page') ?>" href="/">Home</a>
            <span class="breadcrumbs-separator"> </span>
        </li>
        <li class="my-account">
            <strong><?php echo $this->__('My Account') ?></strong>
        </li>
    </ul>
</div>
<div class="account-login<?php if (!$this->helper('customer')->isRegistrationAllowed()) echo ' login-only' ?>">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        <div class="fieldset">
            <div class="col2-set">
                <div class="col-1 registered-users">
                    <h2 class="legend"><?php echo $this->__('Sign In') ?></h2>
                    <div class="login-wrapper">
                        <span class="block-header"><?php echo $this->__('Registered Customers') ?></span>
                        <span class="block-descr"><?php echo $this->__('If you have an account with us, please login.') ?></span>
                        <ul class="form-list">
                            <li>
                                <div class="input-box">
                                    <input placeholder="email address" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" type="text" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                                </div>
                            </li>
                            <li>
                                <div class="input-box">
                                    <input placeholder="password" name="login[password]" type="password" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                                </div>
                            </li>
                            <?php echo $this->getChildHtml('form.additional.info'); ?>
                            <li class="note">
                                <a href="<?php echo $this->getForgotPasswordUrl() ?>"><?php echo $this->__('Forgot Your Password?') ?></a>
                            </li>
                            <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                            <li class="buttons-set">
                                <button type="submit" class="button" name="send" id="send2"><span><span><?php echo $this->__('Sign In') ?></span></span></button>
                            </li>
                            <li class="note facebook">
                                <?php echo $this->getChildHtml('sign_in_facebook_button'); ?>
                            </li>
                        </ul>
                    </div>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                </div>
                <?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
                     <div class="col-2 new-users">
                        <span class="block-header"><?php echo $this->__('New Customer? Register Now') ?></span>
                        <span class="block-descr"><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></span>
                        <h2 class="legend"><?php echo $this->__('Sign Up') ?></h2>
                        <div class="reg-wrapper">
                            <ul class="form-list">
                                <li class="buttons-set">
                                    <button type="button" class="button" onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';"><span><span><?php echo $this->__('Register Now') ?></span></span></button>
                                </li>
                                <li class="note facebook">
                                    <?php echo $this->getChildHtml('sign_up_facebook_button'); ?>
                                </li>
                            </ul>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>
