<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<?php $comments = $this->getComments() ?>
<?php if (count($comments) > 0): ?>
	<ul class="comment-list<?php if ($this->getParentId()): ?> children<?php endif; ?>">
		<?php foreach($comments as $comment): ?>
			<li class="comment" id="comment-<?php echo $comment->getId() ?>">
                <a href="<?php echo $comment->getUrl() ?>" rel="nofollow" class="comment-when"></a>
				<div class="comment-inner">
					<?php if ($comment->getGravatarUrl()): ?>
						<div class="gravatar">
							<img src="<?php echo $comment->getGravatarUrl() ?>" alt="<?php echo $this->escapeHtml($comment->getCommentAuthor()) ?>" />
						</div>
					<?php endif; ?>
                    <div class="comment-entry entry"><?php echo nl2br($this->escapeHtml($comment->getCommentContent())) ?></div>

					<div class="comment-meta">
                        <span class="col-1">
                            <?php echo $this->__('Posted By') ?>
                            <?php if ($comment->getCommentAuthorUrl() !== '#'): ?>
                                <a href="<?php echo $this->escapeHtml($comment->getCommentAuthorUrl()) ?>" rel="nofollow" class="comment-url"><?php echo $this->escapeHtml($comment->getCommentAuthor()) ?></a>
                            <?php else: ?>
                                <?php echo $this->escapeHtml($comment->getCommentAuthor()) ?>
                            <?php endif; ?>
                        </span>
                        <span class="col-2">
                            <?php echo date('dS F Y \a\t g:jA', strtotime($post->getData('post_date'))) ?>

                        </span>
                        <span class="col-3">
                            <?php if ($this->canComment()): ?>
                                <div class="reply">
                                    <a href="<?php echo $this->getPost()->getPermalink() ?>?replytocom=<?php echo $comment->getId() ?>#respond" class="comment-reply-link"><?php echo $this->__('Reply') ?></a>
                                </div>
                            <?php endif; ?>
                        </span>
					</div>




				</div>
				<?php echo $this->getChildrenCommentsHtml($comment) ?>
			</li>
		<?php endforeach; ?>
	</ul>
<?php endif; ?>