<?php

/* @var $this Mage_Wishlist_Block_Customer_Wishlist_Item_Column_Cart */
/* @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();
?>
<div class="add-to-cart-alt">
    <?php if ($product->isSaleable()): ?>
        <button type="button" title="<?php echo $this->__('Add to Bag') ?>" onclick="addWItemToCart(<?php echo $item->getId()?>);"><?php echo $this->__('Add to Bag') ?></button>
    <?php else: ?>
        <?php if ($product->getIsSalable()): ?>
            <p class="availability in-stock"><span><?php echo $this->__('In stock') ?></span></p>
        <?php else: ?>
            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
        <?php endif; ?>
    <?php endif; ?>
</div>
