<?php

/* @var $this Mage_Wishlist_Block_Customer_Wishlist_Item_Column_Cart */
/* @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();
/*
    $options = $this->getChild('customer.wishlist.item.options')
        ->setItem($item)
        ->getConfiguredOptions();
 */
?>

<div class="cart-cell">
    <?php /*
    <?php echo $this->getPriceHtml($product, empty($options));?>
     */ ?>
    <?php /*
        <dl>
            <dt>Colour</dt>
            <dd><?php echo $product->getAttributeText('colour') ?></dd>
        </dl>
        <dl>
            <dt>Size</dt>
            <dd><?php echo $product->getAttributeText('size') ?></dd>
        </dl>
    */ ?>
    <?php if ($item->canHaveQty() && $item->getProduct()->isVisibleInSiteVisibility()): ?>
        <div class="select-box">
            <?php $qty = (int) Mage::getStoreConfig('catalog/product_detail/qty') ?>
            <?php if ($qty): ?>
                <select name="qty[<?php echo $item->getId() ?>]" id="qty<?php echo $item->getId() ?>" class="required-entry input-text qty">
                    <?php for($i = 1; $i <= $qty; $i++): ?>
                        <option <?php if($this->getAddToCartQty($item) * 1 == $i): ?>selected="selected"<?php endIf; ?> value="<?php echo $i ?>"><?php echo $i ?></option>
                    <?php endFor; ?>
                </select>
                <script>
                    jQuery('#qty<?php echo $item->getId() ?>').customSelect();
                </script>
            <?php else: ?>
                <input type="text" class="input-text qty validate-not-negative-number" name="qty[<?php echo $item->getId() ?>]" value="<?php echo $this->getAddToCartQty($item) * 1 ?>" />
            <?php endif; ?>
        </div>
    <?php endif; ?>
    
    <?php foreach($this->getSortedChildren() as $childName):?>
        <?php echo $this->getChildHtml($childName, false);?>
    <?php endforeach;?>
    <?php /*
        <?php if ($product->isVisibleInSiteVisibility()): ?>
           <p><a class="link-edit" href="<?php echo $this->getItemConfigureUrl($item) ?>"><?php echo $this->__('Edit') ?></a></p>
       <?php endif ?>
     */?>
</div>
