
<?php
    /* @var $this RonisBT_Cms_Block_Page */
?>

<?php $_afHelper = Mage::helper('adminforms/image') ?>
<?php $afModel = $this->getPage()->getBlockModel() ?>


<?php $videoCode = $this->getLpIprVideo() ?>
<div <?php if($videoCode): ?>class="video-panel"<?php endIf; ?>>
    <?php if($videoCode): ?>
        <div class="video-wrapper">
            <iframe width="<?php echo $this->stripTags($this->getLpIprWidth()) ?>px" height="<?php echo $this->escapeHtml($this->getLpIprHeight()) ?>px" class="fvideo" src="" data-src="<?php echo Mage::helper('evisu_homepage')->getVideoUrlByCode($videoCode) ?>" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
        </div>
        <a href="#" class="video-overlay-holder"></a>
    <?php endIf; ?>
    <?php if($this->getLpIprImage()): ?>
        <div class="image-holder">
            <img width="<?php echo $this->escapeHtml($this->getLpIprWidth()) ?>px" height="<?php echo $this->escapeHtml($this->getLpIprHeight()) ?>px" src="<?php echo $_afHelper->init($afModel, $this->getLpIprImage() , '')->resize($this->getLpIprWidth(), $this->getLpIprHeight()); ?>" alt="" />
        </div>
    <?php endIf; ?>
</div>
<div class="text-holder">
    <h2>
        <?php echo $this->escapeHtml($this->getLpIprHeader()) ?>&nbsp;
        <span><?php echo $this->escapeHtml($this->getLp3IprTitle()) ?></span>
    </h2>
    <p><?php echo nl2br($this->escapeHtml($this->getLpIprText())) ?></p>
    <a href="<?php echo $this->escapeHtml($this->getLpIprTargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getLpIprLinkText()) ?>"><?php echo $this->escapeHtml($this->getLpIprLinkText()) ?></a>
</div>

