
<?php
    /* @var $this RonisBT_Cms_Block_Page */
?>
<?php $_afHelper = Mage::helper('adminforms/image') ?>
<?php $afModel = $this->getPage()->getBlockModel() ?>
<?php if($this->getLpIpTopText()): ?>
    <div class="top-text"><?php echo nl2br($this->stripTags($this->getLpIpTopText())) ?></div>
<?php endIf; ?>
<?php $videoCode = $this->getLpIpVideo() ?>
<div <?php if($videoCode): ?>class="video-panel"<?php endIf; ?>>
    <?php if($videoCode): ?>
        <div class="video-wrapper">
            <iframe width="<?php echo $this->stripTags($this->getLpIpWidth()) ?>px" height="<?php echo $this->stripTags($this->getLpIpHeight()) ?>px" class="fvideo" src="" data-src="<?php echo Mage::helper('evisu_homepage')->getVideoUrlByCode($videoCode) ?>" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
        </div>
        <a href="#" class="video-overlay-holder"></a>
    <?php endIf; ?>
    <?php if($this->getLpIpImage()): ?>
        <div class="image-holder">
            <img width="<?php echo $this->stripTags($this->getLpIpWidth()) ?>px" height="<?php echo $this->stripTags($this->getLpIpHeight()) ?>px" src="<?php echo $_afHelper->init($afModel, $this->getLpIpImage() , '')->resize($this->getLpIpWidth(), $this->getLpIpHeight()); ?>" alt="" />
        </div>
    <?php endIf; ?>
    <?php $linkText = $this->stripTags($this->getLpIpLinkText()); if($linkText && $this->getLpIpTargetUrl()): ?>
        <a href="<?php echo $this->stripTags($this->getLpIpTargetUrl()) ?>" class="text-link" title="<?php echo $this->stripTags($this->getLpIpLinkText()) ?>">
            <span class="text-link-holder">
                <span class="text-link-wrapper">
                    <?php echo $this->stripTags($this->getLpIpLinkText()) ?>
                </span>
            </span>
        </a>
    <?php elseif(!$linkText && $this->getLpIpTargetUrl()): ?>
        <a href="<?php echo $this->stripTags($this->getLpIpTargetUrl()) ?>"></a>
    <?php endIf; ?>
</div>
<?php if($this->getLpIpBottomText()): ?>
    <div class="bottom-text"><?php echo nl2br($this->stripTags($this->getLpIpBottomText())) ?></div>
<?php endIf; ?>