
<?php
    /* @var $this RonisBT_Cms_Block_Page */
?>
<?php
    $imageWidth = 136;
    $imageHeight = 311;
?>

<?php $_afHelper = Mage::helper('adminforms/image') ?>
<?php $afModel = $this->getPage()->getBlockModel() ?>

<div class="image-holder image-1">
    <a href="<?php echo $this->escapeHtml($this->getLpPpX2sImage1TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getLpPpX2sImage1LinkTitle()) ?>">
        <img width="<?php echo $imageWidth ?>px" height="<?php echo $imageHeight ?>px" src="<?php echo $_afHelper->init($afModel, $this->getLpPpX2sImage1() , '')->resize($imageWidth, $imageHeight); ?>" alt="" />
    </a>
</div>
<div class="image-holder image-2">
    <a href="<?php echo $this->escapeHtml($this->getLpPpX2sImage2TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getLpPpX2sImage2LinkTitle()) ?>">
        <img width="<?php echo $imageWidth ?>px" height="<?php echo $imageHeight ?>px" src="<?php echo $_afHelper->init($afModel, $this->getLpPpX2sImage2() , '')->resize($imageWidth, $imageHeight); ?>" alt="" />
    </a>
</div>
<?php if($this->getLpPpX2sTbLinkText() && $this->getLpPpX2sTbTargetUrl()): ?>
    <a class="<?php echo $this->escapeHtml($this->getLpPpX2sTbBgColor()) ?> category-link" href="<?php echo $this->escapeHtml($this->getLpPpX2sTbTargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getLpPpX2sTbLinkText()) ?>">
        <?php echo $this->escapeHtml($this->getLpPpX2sTbLinkText()) ?>
    </a>
<?php endIf; ?>
<?php if($this->getLpPpX2sAddText()): ?>
    <div class="add-text">
        <p><?php echo $this->escapeHtml($this->getLpPpX2sAddText()) ?></p>
    </div>
<?php endIf; ?>
