
<?php
    /* @var $this RonisBT_Cms_Block_Page */
?>

<?php
    $imageWidth = 394;
    $imageHeight = 394;
?>

<?php $_afHelper = Mage::helper('adminforms/image') ?>
<?php $afModel = $this->getPage()->getBlockModel() ?>
<div class="image-holder image-1">
    <a href="<?php echo $this->escapeHtml($this->getLpPpX4Image1TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getLpPpX4Image1LinkTitle()) ?>">
        <img width="<?php echo $imageWidth ?>px" height="<?php echo $imageHeight ?>px" src="<?php echo $_afHelper->init($afModel, $this->getLpPpX4Image1(), '')->resize($imageWidth, $imageHeight); ?>" alt="" />
    </a>
</div>
<div class="image-holder image-2">
    <a href="<?php echo $this->escapeHtml($this->getLpPpX4Image2TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getLpPpX4Image2LinkTitle()) ?>">
        <img width="<?php echo $imageWidth ?>px" height="<?php echo $imageHeight ?>px" src="<?php echo $_afHelper->init($afModel, $this->getLpPpX4Image2(), '')->resize($imageWidth, $imageHeight); ?>" alt="" />
    </a>
</div>
<div class="image-holder image-3">
    <a href="<?php echo $this->escapeHtml($this->getLpPpX4Image3TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getLpPpX4Image3LinkTitle()) ?>">
        <img width="<?php echo $imageWidth ?>px" height="<?php echo $imageHeight ?>px" src="<?php echo $_afHelper->init($afModel, $this->getLpPpX4Image3(), '')->resize($imageWidth, $imageHeight); ?>" alt="" />
    </a>
</div>
<div class="image-holder image-4">
    <a href="<?php echo $this->escapeHtml($this->getLpPpX4Image4TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getLpPpX4Image4LinkTitle()) ?>">
        <img width="<?php echo $imageWidth ?>px" height="<?php echo $imageHeight ?>px" src="<?php echo $_afHelper->init($afModel, $this->getLpPpX4Image4(), '')->resize($imageWidth, $imageHeight); ?>" alt="" />
    </a>
</div>
<?php if($this->getLpPpX4TbLinkText() && $this->getLpPpX4TbTargetUrl()): ?>
    <a class="<?php echo $this->escapeHtml($this->getLpPpX4TbBgColor()) ?> category-link" href="<?php echo $this->escapeHtml($this->getLpPpX4TbTargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getLpPpX4TbLinkText()) ?>">
        <?php echo $this->escapeHtml($this->getLpPpX4TbLinkText()) ?>
    </a>
<?php endIf; ?>
<?php if($this->getLpPpX4AddText()): ?>
    <div class="add-text">
        <p><?php echo $this->escapeHtml($this->getLpPpX4AddText()) ?></p>
    </div>
<?php endIf; ?>
