
<?php
    /* @var $this RonisBT_Cms_Block_Page */
?>

<?php
    $imageWidth = 372;
    $imageHeight = 808;
?>

<?php $_afHelper = Mage::helper('adminforms/image') ?>
<?php $afModel = $this->getPage()->getBlockModel() ?>

<div class="image-holder image-1">
    <a href="<?php echo $this->escapeHtml($this->getLpPpX2Image1TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getLpPpX2Image1LinkTitle()) ?>">
        <img width="<?php echo $imageWidth ?>px" height="<?php echo $imageHeight ?>px" src="<?php echo $_afHelper->init($afModel, $this->getLpPpX2Image1() , '')->resize($imageWidth, $imageHeight); ?>" alt="" />
    </a>
</div>
<div class="image-holder image-2">
    <a href="<?php echo $this->escapeHtml($this->getLpPpX2Image2TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getLpPpX2Image2LinkTitle()) ?>">
        <img width="<?php echo $imageWidth ?>px" height="<?php echo $imageHeight ?>px" src="<?php echo $_afHelper->init($afModel, $this->getLpPpX2Image2() , '')->resize($imageWidth, $imageHeight); ?>" alt="" />
    </a>
</div>
<?php if($this->getLpPpX2TbLinkText() && $this->getLpPpX2TbTargetUrl()): ?>
    <a class="<?php echo $this->escapeHtml($this->getLpPpX2TbBgColor()) ?> category-link" href="<?php echo $this->escapeHtml($this->getLpPpX2TbTargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getLpPpX2TbLinkText()) ?>">
        <?php echo $this->escapeHtml($this->getLpPpX2TbLinkText()) ?>
    </a>
<?php endIf; ?>
<?php if($this->getLpPpX2AddText()): ?>
    <div class="add-text">
        <p><?php echo $this->escapeHtml($this->getLpPpX2AddText()) ?></p>
    </div>
<?php endIf; ?>
