
<?php
    /* @var $this RonisBT_Cms_Block_Page */
?>
<?php $_afHelper = Mage::helper('adminforms/image') ?>
<?php $afModel = $this->getPage()->getBlockModel() ?>

<?php $videoCode = $this->getHpIpVideo() ?>
<div <?php if($videoCode): ?>class="video-panel"<?php endIf; ?>>
    <?php if($videoCode): ?>
        <div class="video-wrapper">
            <iframe class="fvideo" src="<?php echo Mage::helper('evisu_homepage')->getVideoUrlByCode($videoCode) ?>" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
        </div>
        <a href="#" class="video-overlay-holder"></a>
    <?php endIf; ?>
    <?php if($this->getHpIpImage()): ?>
        <div class="image-holder">
            <img src="<?php echo $_afHelper->init($afModel, $this->getHpIpImage() , '')->resize($this->getWidth(), $this->getHeight()); ?>" alt="" />
        </div>
    <?php endIf; ?>
    <?php $linkText = $this->getHpIpLinkText(); if($linkText && $this->getHpIpTargetUrl()): ?>
        <a href="<?php echo $this->escapeHtml($this->getHpIpTargetUrl()) ?>" class="text-link" title="<?php echo $this->escapeHtml($this->getHpIpLinkText()) ?>">
            <span class="text-link-holder">
                <span class="text-link-wrapper">
                    <?php echo $this->escapeHtml($this->getHps1Ip1LinkText()) ?>
                </span>
            </span>
        </a>
    <?php elseif(!$linkText && $this->getHpIpTargetUrl()): ?>
        <a href="<?php echo $this->escapeHtml($this->getHpIpTargetUrl()) ?>"></a>
    <?php endIf; ?>
</div>