
<?php
    /* @var $this RonisBT_Cms_Block_Page */
?>
<?php $i = 1; ?>
<?php $sections = $this->getSections() ?>
<?php if(count($sections) > 0): ?>
    <?php foreach ($this->getSections() as $_section): ?>
        <div class="block-<?php echo $i ?> <?php echo $_section->getPageType() ?>">
            <?php echo $_section->toHtml(); ?>
        </div>
        <?php $i++; ?>
    <?php endforeach ?>
<?php endIf; ?>