
<?php
/* @var $this RonisBT_Cms_Block_Page */
?>

<?php $i = 1; ?>
<?php $sections = $this->getSections() ?>
<?php if(count($sections) > 0): ?>
    <?php foreach ($this->getSections() as $_block): ?>
        <div style="z-index:1;
            <?php if($_block->getHTbWidth()): ?>width:<?php echo $_block->getHTbWidth() ?>;<?php endIf; ?>
            <?php if($_block->getHTbMinHeight()): ?>min-height:<?php echo $_block->getHTbMinHeight() ?>;<?php endIf; ?>
            <?php if($_block->getHLeft()): ?>left:<?php echo $_block->getHLeft() ?>;<?php endIf; ?>
            <?php if($_block->getHRight()): ?>right:<?php echo $_block->getHRight() ?>;<?php endIf; ?>
            <?php if($_block->getHTop()): ?>top:<?php echo $_block->getHTop() ?>;<?php endIf; ?>
            "
            class="item item-<?php echo $i ?> <?php echo $_block->getPageType() ?> <?php echo $_block->getHImageType() ?>">
            <?php echo $_block->toHtml(); ?>
        </div>
        <?php $i++; ?>
    <?php endforeach ?>
<?php endIf; ?>
