<?php /* @var $this Idev_OneStepCheckout_Block_Summary */ ?>
<?php
$_coreHelper = $this->helper('core');
$checkoutHelper = Mage::helper('onestepcheckout/checkout');
?>
<div class="summary-tables">
    <table class="onestepcheckout-summary">
        <thead>
            <tr>
                <th class="name"><?php echo $this->__('Product'); ?></th>
                <th class="size"><?php echo $this->__('Size'); ?></th>
                <th class="colour"><?php echo $this->__('CLR'); ?></th>
                <th class="qty"><?php echo $this->__('Qty'); ?></th>
                <th class="total"><?php echo $this->__('Subtotal'); ?></th>
            </tr>
        </thead>
        <?php foreach($this->getItems() as $item): ?>
        <tr>
            <td class="name">
                <?php //var_dump(array_keys($item->getProduct()->getData())) ?>
                <span class="product-name"><?php echo $item->getName(); ?></span>
                <?php if($checkoutHelper->settings['show_custom_options']): ?>
                    <?php $options = $item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct()); ?>
                    <?php if(isset($options['options']) && count($options['options']) > 0): ?>
                    <ul class="onestepcheckout-custom-options">
                    <?php foreach($options['options'] as $option): ?>
                        <li><b><?php echo $option['label'] . ':</b> ' . $option['value']; ?></li>
                    <?php endforeach; ?>
                    </ul>
                    <?php endif; ?>

                    <?php if($item->getProduct()->isConfigurable()): ?>

                    <?php
                    $configurable_options = $item->getProduct()->getTypeInstance(true)->getSelectedAttributesInfo($item->getProduct());
                    ?>

                    <?php if(is_array($configurable_options) && count($configurable_options) > 0): ?>
                    <ul class="onestepcheckout-custom-options">
                    <?php foreach($configurable_options as $option): ?>
                        <li><b><?php echo $option['label']; ?>:</b> <?php echo $option['value']; ?></li>
                    <?php endforeach; ?>
                    </ul>
                    <?php endif; ?>

                    <?php endif; ?>

                <?php endif; ?>
            </td>
            <td class="size"><?php echo $item->getProduct()->getAttributeText('size') ?></td>
            <td class="colour"><?php echo $item->getProduct()->getAttributeText('colour') ?></td>
            <td class="qty"><?php echo $item->getQty() ?></td>
            <td class="total">
                <?php if($checkoutHelper->settings['display_tax_included']): ?>
                <?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getSubtotalInclTax($item)); ?>
                <?php else: ?>
                <?php echo $this->helper('checkout')->formatPrice($item->getRowTotal()); ?>
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>

    <table class="onestepcheckout-totals">
        <?php foreach($this->getTotals() as $total): ?>
            <?php if(!$total->getTitle()){continue;}?>
                <?php
                    $fullInfo = $total->getFullInfo();

                    if(!empty($fullInfo) && $checkoutHelper->settings['display_full_tax']):
                        foreach ($fullInfo as $info):
                            $rates = current($info['rates']);
                            $amount = $info['amount'];
                ?>
                            <tr>
                                <td class="title"><?php echo $rates['title'] ?> (<?php echo $rates['percent'] ?>%)</td><td class="value"><?php echo $this->helper('checkout')->formatPrice($amount); ?></td>
                            </tr>
                    <?php endforeach;
                endif;?>
            <tr<?php if($total->getCode() == 'grand_total'): ?> class="grand-total"<?php endif; ?>>
                <td class="title">
                    <?php

                    $code = $total->getCode();
                    $value = $total->getValue();

                    if($code == 'subtotal')    {
                        $total_name = $this->__('Subtotal');
                    }
                    elseif($code == 'shipping')    {
                        $total_name = $this->__('Delivery');
                        if($checkoutHelper->settings['display_tax_included'])   {
                            $value += $this->getQuote()->getShippingAddress()->getShippingTaxAmount();
                        }
                    }
                    elseif($code == 'grand_total')    {
                        $total_name = $this->__('Total');
                    }
                    else{
                        $total_name = $total->getTitle();
                    }

                    echo $total_name;

                    ?>
                </td>
                <td class="value">
                    <?php echo $this->helper('checkout')->formatPrice($value); ?>
                </td>
            </tr>
        <?php endforeach; ?>
        <tr><td colspan="100"><?php echo $this->__('Price includes VAT')?></td></tr>
    </table>
</div>
<div class="onestepcheckout-summary-message-wrapper">
    <p>
        Your credit card will be charged <?php echo $this->helper('checkout')->formatPrice($value); ?>.
        Where your card transactions are denominated in currency other then GBP the amount you are actually charged will depend on the exchange rate and other charges applied by your card issuer.
    </p>
</div>
<script type="text/javascript">
//<![CDATA[
var total = <?php echo $this->getGrandTotal();?>;
    if(payment.reloadcallback){
        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/paymentrefresh', array('_secure'=>true)); ?>';
        paymentrefresh(url);
        payment.countreload = 0;
        payment.reloadcallback = false;
    }
//]]>
</script>
