<?php

class Mage_Page_Model_Geocountries {

    public $swichableCountries = null;

    public function getSwichableCountries(){
        if(is_null($this->swichableCountries))
        {
            $this->swichableCountries = array();
            foreach($this->getConfig() as $row){
                if(count($row) == 5){
                    $country = new Varien_Object();
                    $country->setCode($row[0]);
                    $country->setName($row[1]);
                    $country->setStore($row[2]);
                    $country->setCurrency($row[3]);
                    $country->setOrigin($row[4]);
                    $this->swichableCountries[] = $country;
                }
            }
        }
        return $this->swichableCountries;
    }

    public function getConfig(){
        /*Country Code, Country Name, Store Code, Currency Code, Delivery Origin */
        $config = array(
            array('AS','American Samoa'),
            array('AD','Andorra'),
            array('AO','Angola'),
            array('AI','Anguilla'),
            array('AQ','Antarctica'),
            array('AG','Antigua and Barbuda'),
            array('AR','Argentina','asia','USD','Hong Kong'),
            array('AM','Armenia'),
            array('AW','Aruba'),
            array('AU','Australia','asia','USD','Hong Kong'),
            array('AT','Austria','eu','EUR','United Kingdom'),
            array('AZ','Azerbaijan'),
            array('BS','Bahamas'),
            array('BH','Bahrain','asia','USD','Hong Kong'),
            array('BD','Bangladesh'),
            array('BB','Barbados'),
            array('BY','Belarus'),
            array('BE','Belgium','eu','EUR','United Kingdom'),
            array('BZ','Belize'),
            array('BJ','Benin'),
            array('BM','Bermuda'),
            array('BT','Bhutan'),
            array('BO','Bolivia'),
            array('BA','Bosnia and Herzegovina'),
            array('BW','Botswana'),
            array('BV','Bouvet Island'),
            array('BR','Brazil','asia','USD','Hong Kong'),
            array('IO','British Indian Ocean Territory'),
            array('VG','British Virgin Islands'),
            array('BN','Brunei','asia','USD','Hong Kong'),
            array('BG','Bulgaria','eu','EUR','United Kingdom'),
            array('BF','Burkina Faso'),
            array('BI','Burundi'),
            array('KH','Cambodia','asia','USD','Hong Kong'),
            array('CM','Cameroon'),
            array('CA','Canada','asia','USD','Hong Kong'),
            array('CV','Cape Verde'),
            array('KY','Cayman Islands'),
            array('CF','Central African Republic'),
            array('TD','Chad'),
            array('CL','Chile','asia','USD','Hong Kong'),
            //array('CN','China','eu','USD','United Kingdom'),
            array('CN','China','asia','USD','Hong Kong'),
            array('CX','Christmas Island'),
            array('CC','Cocos [Keeling] Islands'),
            array('CO,Colombia'),
            array('KM','Comoros'),
            array('CG','Congo - Brazzaville'),
            array('CD','Congo - Kinshasa'),
            array('CK','Cook Islands'),
            array('CR','Costa Rica','asia','USD','Hong Kong'),
            array('HR','Croatia'),
            array('CU','Cuba','asia','USD','Hong Kong'),
            array('CY','Cyprus','eu','EUR','United Kingdom'),
            array('CZ','Czech Republic','eu','EUR','United Kingdom'),
            array('CI','Côte d’Ivoire'),
            array('DK','Denmark','eu','EUR','United Kingdom'),
            array('DJ','Djibouti'),
            array('DM','Dominica'),
            array('DO','Dominican Republic','asia','USD','Hong Kong'),
            array('EC','Ecuador'),
            array('EG','Egypt','asia','USD','Hong Kong'),
            array('SV','El Salvador'),
            array('GQ','Equatorial Guinea'),
            array('ER','Eritrea'),
            array('EE','Estonia','eu','EUR','United Kingdom'),
            array('ET','Ethiopia'),
            array('FK','Falkland Islands'),
            array('FO','Faroe Islands'),
            array('FJ','Fiji'),
            array('FI','Finland','eu','EUR','United Kingdom'),
            array('FR','France','eu','EUR','United Kingdom'),
            array('GF,French Guiana'),
            array('PF','French Polynesia'),
            array('TF','French Southern Territories'),
            array('GA','Gabon'),
            array('GM','Gambia','asia','USD','Hong Kong'),
            array('GE','Georgia'),
            array('DE','Germany','eu','EUR','United Kingdom'),
            array('GH','Ghana'),
            array('GI','Gibraltar'),
            array('GR','Greece','eu','EUR','United Kingdom'),
            array('GL','Greenland','asia','USD','Hong Kong'),
            array('GD','Grenada'),
            array('GP','Guadeloupe'),
            array('GU','Guam'),
            array('GT','Guatemala'),
            array('GG','Guernsey'),
            array('GN','Guinea'),
            array('GW','Guinea-Bissau'),
            array('GY','Guyana'),
            array('HT','Haiti'),
            array('HM','Heard Island and McDonald Islands'),
            array('HN','Honduras'),
            array('HK','Hong Kong','asia','USD','Hong Kong'),
            array('HU','Hungary','eu','EUR','United Kingdom'),
            array('IS','Iceland'),
            array('IN','India','asia','USD','Hong Kong'),
            array('ID','Indonesia','asia','USD','Hong Kong'),
            array('IR','Iran'),
            array('IQ','Iraq'),
            array('IE','Ireland','eu','EUR','United Kingdom'),
            array('IM','Isle of Man'),
            array('IL','Israel','eu','EUR','United Kingdom'),
            array('IT','Italy','eu','EUR','United Kingdom'),
            array('JM','Jamaica','asia','USD','Hong Kong'),
            array('JP','Japan'),
            array('JE','Jersey'),
            array('JO','Jordan','asia','USD','Hong Kong'),
            array('KZ','Kazakhstan'),
            array('KE','Kenya','asia','USD','Hong Kong'),
            array('KI','Kiribati'),
            array('KW','Kuwait','asia','USD','Hong Kong'),
            array('KG','Kyrgyzstan'),
            array('LA','Laos','asia','USD','Hong Kong'),
            array('LV','Latvia','eu','EUR','United Kingdom'),
            array('LB','Lebanon','asia','USD','Hong Kong'),
            array('LS','Lesotho'),
            array('LR','Liberia'),
            array('LY','Libya'),
            array('LI','Liechtenstein'),
            array('LT','Lithuania','eu','EUR','United Kingdom'),
            array('LU','Luxembourg','eu','EUR','United Kingdom'),
            array('MO','Macau SAR China','asia','USD','Hong Kong'),
            array('MK','Macedonia'),
            array('MG','Madagascar'),
            array('MW','Malawi'),
            array('MY','Malaysia','asia','USD','Hong Kong'),
            array('MV','Maldives','asia','USD','Hong Kong'),
            array('ML','Mali'),
            array('MT','Malta','eu','EUR','United Kingdom'),
            array('MH','Marshall Islands'),
            array('MQ','Martinique'),
            array('MR','Mauritania'),
            array('MU','Mauritius','asia','USD','Hong Kong'),
            array('YT','Mayotte'),
            array('MX','Mexico','asia','USD','Hong Kong'),
            array('FM','Micronesia'),
            array('MD','Moldova'),
            array('MC','Monaco'),
            array('MN','Mongolia'),
            array('ME','Montenegro'),
            array('MS','Montserrat'),
            array('MA','Morocco','asia','USD','Hong Kong'),
            array('MZ','Mozambique','asia','USD','Hong Kong'),
            array('MM','Myanmar [Burma]','asia','USD','Hong Kong'),
            array('NA','Namibia','asia','USD','Hong Kong'),
            array('NR','Nauru'),
            array('NP','Nepal','asia','USD','Hong Kong'),
            array('NL','Netherlands','eu','EUR','United Kingdom'),
            array('AN','Netherlands Antilles'),
            array('NC','New Caledonia'),
            array('NZ','New Zealand','asia','USD','Hong Kong'),
            array('NI','Nicaragua'),
            array('NE','Niger'),
            array('NG','Nigeria'),
            array('NU','Niue'),
            array('NF','Norfolk Island'),
            array('KP','North Korea'),
            array('MP','Northern Mariana Islands'),
            array('NO','Norway','eu','EUR','United Kingdom'),
            array('OM','Oman','asia','USD','Hong Kong'),
            array('PK','Pakistan'),
            array('PW','Palau'),
            array('PS','Palestinian Territories'),
            array('PA','Panama'),
            array('PG','Papua New Guinea'),
            array('PY','Paraguay'),
            array('PE','Peru'),
            array('PH','Philippines','asia','USD','Hong Kong'),
            array('PN','Pitcairn Islands'),
            array('PL','Poland','eu','EUR','United Kingdom'),
            array('PT','Portugal','eu','EUR','United Kingdom'),
            array('PR','Puerto Rico','asia','USD','Hong Kong'),
            array('QA','Qatar','asia','USD','Hong Kong'),
            array('RO','Romania','eu','EUR','United Kingdom'),
            array('RU','Russia','eu','EUR','United Kingdom'),
            array('RW','Rwanda'),
            array('RE','Réunion'),
            array('BL','Saint Barthélemy'),
            array('SH','Saint Helena'),
            array('KN','Saint Kitts and Nevis'),
            array('LC','Saint Lucia'),
            array('MF','Saint Martin'),
            array('PM','Saint Pierre and Miquelon'),
            array('VC','Saint Vincent and the Grenadines'),
            array('WS','Samoa'),
            array('SM','San Marino'),
            array('SA','Saudi Arabia','asia','USD','Hong Kong'),
            array('SN','Senegal','asia','USD','Hong Kong'),
            array('RS','Serbia'),
            array('SC','Seychelles','asia','USD','Hong Kong'),
            array('SL','Sierra Leone'),
            array('SG','Singapore','asia','USD','Hong Kong'),
            array('SK','Slovakia','eu','EUR','United Kingdom'),
            array('SI','Slovenia','eu','EUR','United Kingdom'),
            array('SB','Solomon Islands'),
            array('SO','Somalia'),
            array('ZA','South Africa','asia','USD','Hong Kong'),
            array('GS','South Georgia and the South Sandwich Islands'),
            array('KR','South Korea'),
            array('ES','Spain','eu','EUR','United Kingdom'),
            array('LK','Sri Lanka','asia','USD','Hong Kong'),
            array('SD','Sudan'),
            array('SR','Suriname','asia','USD','Hong Kong'),
            array('SJ','Svalbard and Jan Mayen'),
            array('SZ','Swaziland'),
            array('SE','Sweden','eu','EUR','United Kingdom'),
            array('CH','Switzerland','eu','EUR','United Kingdom'),
            array('SY','Syria','asia','USD','Hong Kong'),
            array('ST','São Tomé and Príncipe'),
            array('TW','Taiwan','asia','USD','Hong Kong'),
            array('TJ','Tajikistan'),
            array('TZ','Tanzania'),
            array('TH','Thailand','asia','USD','Hong Kong'),
            array('TL','Timor-Leste'),
            array('TG','Togo'),
            array('TK','Tokelau'),
            array('TO','Tonga'),
            array('TT','Trinidad and Tobago','asia','USD','Hong Kong'),
            array('TN','Tunisia','asia','USD','Hong Kong'),
            array('TR','Turkey'),
            array('TM','Turkmenistan'),
            array('TC','Turks and Caicos Islands'),
            array('TV','Tuvalu'),
            array('UM','U.S. Minor Outlying Islands'),
            array('VI','U.S. Virgin Islands'),
            array('UG','Uganda'),
            array('UA','Ukraine','eu','EUR','United Kingdom'),
            array('AE','United Arab Emirates','asia','USD','Hong Kong'),
            array('GB','United Kingdom','eu','GBP','United Kingdom'),
            array('US','United States','us','USD','United States'),
            array('UY','Uruguay','asia','USD','Hong Kong'),
            array('UZ','Uzbekistan'),
            array('VU','Vanuatu'),
            array('VA','Vatican City'),
            array('VE','Venezuela','asia','USD','Hong Kong'),
            array('VN','Vietnam','asia','USD','Hong Kong'),
            array('WF','Wallis and Futuna'),
            array('EH','Western Sahara'),
            array('YE','Yemen'),
            array('ZM','Zambia'),
            array('ZW','Zimbabwe'),
            array('AX','Åland Islands'),
        );
        return $config;
    }
}
