<?php
/* @var $location MageWorx_GeoIP_Model_Geoip */

$location = Mage::getSingleton('mwgeoip/geoip')->getCurrentLocation();
$countries = Mage::helper('storeswitcher')->getSwitchableCountries();


if (count($countries) > 0): ?>

    <?php if (Mage::helper('storeswitcher')->getSwitcherDisplayMode() == MageWorx_StoreSwitcher_Model_System_Config_Source_Mode::DISPLAY_MODE_NAMES_FLAGS): ?>
        <?php /* Disaply mode: Flags + Names */ ?>
        <div class="form-language">
            <?php /*Delete comment tag to see current store code  ?>
        <div style="color: #fff"><?php echo Mage::app()->getStore()->getCode() ?></div>
        <?php */ ?>
            <label for="select-country"><?php echo $this->__('You are currently shipping to the:') ?></label>
            <?php if(!Mage::helper('storeswitcher')->getForceStoreView()): ?>
                <select id="select-country" class="replacemeselect" title="<?php echo $this->__('Your Shipping Country') ?>">
                    <?php foreach ($countries as $country): ?>
                        <option <?php if($country['value'] == $location->getCode()){ echo 'selected="selected"'; } ?> value="<?php echo $country['value'] ?>" imgsrc="<?php echo Mage::helper('mwgeoip')->getFlagPath($country['value']); ?>"><?php echo $country['label'] ?></option>
                    <?php endforeach; ?>
                </select>

                <script type="text/javascript">
                    var selreplace = new SelectReplace('select-country', {}, '<?php echo Mage::helper('storeswitcher')->getCountryUrl();  ?>');
                </script>
            <?php else: ?>
                <span class="geoip-country"><img src="<?php echo Mage::helper('mwgeoip')->getFlagPath($location->getCode()); ?>" /><?php echo $location->getCountry(); ?></span>
            <?php endif; ?>
        </div>

    <?php elseif (Mage::helper('storeswitcher')->getSwitcherDisplayMode() == MageWorx_StoreSwitcher_Model_System_Config_Source_Mode::DISLPAY_MODE_NAMES): ?>
        <?php /* Display mode: Names */ ?>

        <div class="form-language">
            <?php /* Delete comment tag to see current store code  ?>
        <div style="color: #fff"><?php echo Mage::app()->getStore()->getCode() ?></div>
        <?php  */ ?>
            <?php //if(!Mage::helper('storeswitcher')->getForceStoreView()): ?>
                <div class="country-select-label">
                    <?php
                        $defCountryCode = Mage::getStoreConfig('general/country/default');
                        $defCountry = Mage::getModel('directory/country')->loadByCode($defCountryCode);
                        if(!$displayCountry = $location->getCountry())
                        {
                            $displayCountry = $defCountry->getName();
                        }
                    ?>
                    <?php echo $this->__('You are currently shipping to the:') . ' (<span id="change-country-btn">' . $displayCountry . '('.$location->getCode() . ')' . '</span>)' ?>
                </div>
                <div id="change-country-popup" class="no-display">

                    <div class="close-btn">X</div>
                    <div class="header"><?php echo $this->__('Change Country') ?></div>
                    <div class="description"><?php echo $this->__('Please select the country where your order will be shipped to. This will give you the correct pricing, delivery times and shipping costs for your destination') ?></div>
                    <div class="field-row">
                        <label for="select-country"><?php echo $this->__('Delivery Country: ') ?></label>
                        <select id="select-country" class="replacemeselect">
                            <?php foreach ($countries as $country): ?>
                                <option <?php if($country['value'] == $location->getCode()){ echo 'selected="selected"'; } ?> value="<?php echo $country['value'] ?>"><?php echo $country['label'] ?></option>
                            <?php endforeach; ?>
                        </select>

                    </div>
                    <?php //var_dump($location->getData()) ?>
                    <div class="field-row">
                        <label for=""><?php echo $this->__('Order Billed In: ') ?></label>
                        <span><?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getName() ?></span>
                    </div>
                    <div class="field-row">
                        <label for=""><?php echo $this->__('Order Dispatched From: ') ?></label>
                        <span><?php echo $defCountry->getName() ?></span>
                    </div>
                    <div class="field-row-btn">
                        <button id="change-country-popup-update-btn"><?php echo $this->__('Update') ?></button>
                    </div>
                    <script type="text/javascript">
                        //jQuery('#select-country').customSelect();
                        $('change-country-popup-update-btn').observe('click', function(event){
                            countryCode = $('select-country').value;
                            onChangeUrl = '<?php echo Mage::helper('storeswitcher')->getCountryUrl();  ?>';
                            url = onChangeUrl.replace('%geoip_code%', countryCode);
                            setLocation(url);
                            event.stop();
                        })
                    </script>
                </div>
            <?php //else: ?>
            <?php /*
                <span class="geoip-country"><?php echo $location->getCountry(); ?></span>
                */ ?>
            <?php //endif; ?>
        </div>

    <?php endif; ?>
    <script>
        jQuery('#select-country').customSelect();
    </script>
<?php endif; ?>