<?php
/* @var $location MageWorx_GeoIP_Model_Geoip */

$location = Mage::getSingleton('mwgeoip/geoip')->getCurrentLocation();
$countries = Mage::helper('storeswitcher')->getSwitchableCountries();


if (count($countries) > 0): ?>

    <?php if (Mage::helper('storeswitcher')->getSwitcherDisplayMode() == MageWorx_StoreSwitcher_Model_System_Config_Source_Mode::DISPLAY_MODE_NAMES_FLAGS): ?>
        <?php /* Disaply mode: Flags + Names */ ?>
        <div class="form-language">
            <?php /*Delete comment tag to see current store code  ?>
        <div style="color: #fff"><?php echo Mage::app()->getStore()->getCode() ?></div>
        <?php */ ?>
            <label for="select-country"><?php echo $this->__('You are currently shipping to the:') ?></label>
            <?php if(!Mage::helper('storeswitcher')->getForceStoreView()): ?>
                <select id="select-country" class="replacemeselect" title="<?php echo $this->__('Your Shipping Country') ?>">
                    <?php foreach ($countries as $country): ?>
                        <option <?php if($country['value'] == $location->getCode()){ echo 'selected="selected"'; } ?> value="<?php echo $country['value'] ?>" imgsrc="<?php echo Mage::helper('mwgeoip')->getFlagPath($country['value']); ?>"><?php echo $country['label'] ?></option>
                    <?php endforeach; ?>
                </select>

                <script type="text/javascript">
                    var selreplace = new SelectReplace('select-country', {}, '<?php echo Mage::helper('storeswitcher')->getCountryUrl();  ?>');
                </script>
            <?php else: ?>
                <span class="geoip-country"><img src="<?php echo Mage::helper('mwgeoip')->getFlagPath($location->getCode()); ?>" /><?php echo $location->getCountry(); ?></span>
            <?php endif; ?>
        </div>

    <?php elseif (Mage::helper('storeswitcher')->getSwitcherDisplayMode() == MageWorx_StoreSwitcher_Model_System_Config_Source_Mode::DISLPAY_MODE_NAMES): ?>
        <?php /* Display mode: Names */ ?>

        <div class="form-language">
            <?php /* Delete comment tag to see current store code  ?>
        <div style="color: #fff"><?php echo Mage::app()->getStore()->getCode() ?></div>
        <?php  */ ?>
            <?php if(!Mage::helper('storeswitcher')->getForceStoreView()): ?>
                <label class="label-for-country-select" for="select-country"><?php echo $this->__('You are currently shipping to the: (') ?></label>
                <select id="select-country" class="replacemeselect" title="<?php echo $this->__('You are currently shipping to the ') ?>">
                    <?php foreach ($countries as $country): ?>
                        <option <?php if($country['value'] == $location->getCode()){ echo 'selected="selected"'; } ?> value="<?php echo $country['value'] ?>"><?php echo $country['label'] ?></option>
                    <?php endforeach; ?>
                </select>
                <div class="fl-left">)</div>
                <script type="text/javascript">
                    $('select-country').observe('change', function(event){
                        console.log('change');
                        countryCode = $('select-country').value;
                        onChangeUrl = '<?php echo Mage::helper('storeswitcher')->getCountryUrl();  ?>';
                        url = onChangeUrl.replace('%geoip_code%', countryCode);
                        setLocation(url);
                        event.stop();
                    })
                </script>
            <?php else: ?>
                <span class="geoip-country"><?php echo $location->getCountry(); ?></span>
            <?php endif; ?>
        </div>

    <?php endif; ?>
    <script>
        jQuery('#select-country').customSelect();
    </script>
<?php endif; ?>