<?php /* @var $this Mage_Checkout_Block_Cart_Sidebar */ ?>
<?php
/**
 * Shoping cart sidebar
 *
 * @see Mage_Checkout_Block_Cart_Sidebar
 */
?>
<div class="top-cart-holder">
    <div class="top-cart">
        <?php $_cartQty = $this->getSummaryCount() ?>
        <?php if (!($_cartQty > 0)) $_cartQty = 0; ?>
        <?php $_myCart = $this->__('My Basket (%s)', '<span>' . $_cartQty . '</span>') ?>
        <?php if ($this->getIsLinkMode() || !$this->getIsNeedToDisplaySideBar()):?>
            <div class="block-title no-items">
                <ul class="links cart-link">
                    <li ><a href="<?php echo $this->getUrl('checkout/cart'); ?>"><?php echo $_myCart ?></a></li>
                </ul>
            </div>
        <?php else:?>
            <div class="block-title<?php if(!$_cartQty) { echo (' no-items'); } ?>">
                <strong id="cartHeader"><?php echo $_myCart ?></strong><span class='ajax-basket-loader'></span>
            </div>
            <div id="topCartContent" class="block-content" style="display:none">
                <div class="inner-wrapper"><?php // extra div to smooth slideUp and slideDown ?>
                    <div onclick="Enterprise.TopCart.hideCart();" class="close-btn ajax-basket-close-btn"></div>
                    <span class ="bag-subtitle"><?php echo $this->__('Basket') ?></span>
                    <?php $_items = $this->getRecentItems() ?>
                    <?php if(count($_items) > 0 ): ?>
                        <div class="basket-previous-btn-wrapper"><div id="basket-previous-item"></div></div>
                        <ol id="mini-cart" class="mini-products-list">
                            <?php $i = 0; foreach($_items as $_item): ?>
                                <li class="item" id="ajax-basket-item-<?php echo $i ?>">
                                    <div class="item-holder">
                                        <?php echo $this->getItemHtml($_item) ?>
                                    </div>
                                </li>
                            <?php $i++; endForeach; ?>
                        </ol>
                        <div class="basket-next-btn-wrapper"><div id="basket-next-item"></div></div>
                        <div id="top-cart-messages"></div>
                        <div class ='summary-info'>

                            <div class='items-count'>
                                <span><?php echo $this->__('items:') ?> <?php echo $_cartQty ?></span>
                            </div>
                            <div class="subtotal">
                                <?php if ($this->canApplyMsrp()): ?>
                                    <span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                                <?php else: ?>
                                    <span class="label"><?php echo $this->__('subtotal:') ?></span>
                                    <?php /* @var $this Idev_OneStepCheckout_Block_Checkout_Cart_Sidebar */ ?>
                                    <?php echo preg_replace("/(\.)(\d{1,2})/", ".<sup>\${2}</sup>", Mage::helper('checkout')->formatPrice($this->getSubtotal(false))) ?>
                                    <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                                        / <?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?>
                                        <?php echo Mage::helper('tax')->getIncExcText(true) ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div class="actions">
                            <?php echo $this->getChildHtml('extra_actions') ?>
                            <button class="button" type="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>');"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
                            <a href="<?php echo $this->getUrl('checkout/cart'); ?>"><span><?php echo $this->__('View Basket') ?></span></a>
                        </div>
                    <?php else: ?>
                        <p class="cart-empty">
                            <?php echo $this->__('You have no items in your shopping bag') ?>
                        </p>
                        <?php /*
                            <?php if ($this->getCartEmptyMessage()): ?>
                                <p class="cart-empty cart-empty-message"><?php echo $this->getCartEmptyMessage(); ?></p>
                            <?php endif; ?>
                         */?>
                    <?php endif ?>
                </div>
            </div>
        <script type="text/javascript">
            Enterprise.TopCart.initialize('topCartContent');
            //AjaxBasket.load();//if need resize...
            // Below can be used to show minicart after item added
            //Enterprise.TopCart.showCart(7);
        </script>
        <?php endif;?>
    </div>
    <script>
        AjaxBasket.init(<?php echo $_cartQty ?>);
    </script>
</div>