
<?php
    $columns = $this->getColumns();
     //die(var_dump($columns)));

?>
<div class="data-table" id="wishlist-table">
    <div class="thead">
        <div class="tr">
            <?php foreach ($columns as $column): ?>
                <div class="th"><?php echo $column->getTitle();?></div>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="tbody">
        <?php if (count($this->getItems())): ?>
            <?php foreach ($this->getItems() as $item): ?>
                <div class="tr" id="item_<?php echo $item->getId();?>">
                    <?php foreach ($columns as $column): ?>
                        <div class="td"><?php $column->setItem($item); echo $column->toHtml($item);?></div>
                    <?php endforeach; ?>
                </div>
            <?php endforeach ?>
        <?php else: ?>
            <div class="td" colspan="<?php echo count($columns);?>" class="wishlist-empty"><?php echo $this->__('This Wishlist has no Items');?></div>
        <?php endif; ?>
    </div>
</div>
<?php foreach ($columns as $column): ?>
    <?php echo $column->getAdditionalHtml();?>
<?php endforeach; ?>
<script type="text/javascript">
    //<![CDATA[
        decorateTable('wishlist-table');

    <?php foreach ($columns as $column): ?>
        <?php echo $column->getJs();?>
    <?php endforeach; ?>
    //]]>
</script>
