<?php
/**
 * Appmerce - Applications for Ecommerce
 * http://www.appmerce.com
 *
 * @extension   MasterCard Internet Gateway Service (MIGS) - Virtual Payment Client
 * @type        Payment method
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    Magento Commerce
 * @package     Appmerce_Migs
 * @copyright   Copyright (c) 2011-2013 Appmerce (http://www.appmerce.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
$formData = $this->getFormData();
?>
<p><strong><?php echo Mage::helper('migs')->__('You will be redirected to the payment gateway in a few seconds.'); ?></strong></p>
<div class="cart-logo"><img src="<?php echo $this->getSkinUrl('images/cart-logo.jpg') ?>" alt="cart-logo" /></div>
<form name="migs" id="migs_review_form" action="<?php echo $this->getFormAction();?>" method="post" accept-charset="UTF-8">
  <?php if (is_array($formData)): ?>
    <fieldset>
      <?php foreach ($formData as $name => $value) { ?>
        <input type="hidden" name="<?php echo($name); ?>" value="<?php echo($value); ?>" />
      <?php } ?>
    </fieldset>
  <?php endif; ?>
</form>

<script type="text/javascript">
    //<![CDATA[
        var review = new VarienForm('migs_review_form', '');
        Event.observe(window, 'load', function() {
            review.submit();
        });
    //]]>
</script>
