<?php /* @var $this Mage_Customer_Block_Address_Edit */ ?>


<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Contact Info') ?></h2>
        <div class="block-wrapper">
            <?php echo $this->getBlockHtml('formkey')?>
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <ul class="form-list">
                <li class="fields">
                    <?php echo $this->getNameBlockHtml() ?>
                </li>
                <li>
                    <label for="company"><?php echo $this->__('Company') ?></label>
                    <div class="input-box">
                        <input type="text" name="company" id="company" title="<?php echo $this->__('Company') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="telephone" class="required"><?php echo $this->__('Telephone') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="text" name="telephone" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="telephone" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="fax"><?php echo $this->__('Fax') ?></label>
                        <div class="input-box">
                            <input type="text" name="fax" id="fax" title="<?php echo $this->__('Fax') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" />
                        </div>
                    </div>
                </li>
            </ul>
            <div class="buttons-set form-buttons">
                <button type="submit" class="button" title="<?php echo $this->__('Save') ?>"><span><span><?php echo $this->__('Save') ?></span></span></button>
            </div>
        </div>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Address') ?></h2>
        <div class="block-wrapper">
            <ul class="form-list">
            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <li>
                    <label for="street_1" class="required"><?php echo $this->__('Street Address') ?><em>*</em></label>
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li class="add-field">
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php endfor; ?>
                <li class="fields">
                    <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                    <div class="field">
                        <label for="vat_id"><?php echo $this->__('VAT Number') ?></label>
                        <div class="input-box">
                            <input type="text" name="vat_id" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" id="vat_id" />
                        </div>
                    </div>
                    <?php endif; ?>
                    <div class="field">
                        <label for="city" class="required"><?php echo $this->__('City') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="region_id" class="required"><?php echo $this->__('County') ?><em id="custom-required-region">*</em></label>
                        <div class="input-box">
                            <div id="custom_region_id">
                                <select data-defvalue="Select County" id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                   <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                            </div>
                            <script>
                                jQuery('#region_id').customSelect();
                            </script>
                            <script type="text/javascript">
                                $('region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="zip" class="required"><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="country" class="required"><?php echo $this->__('Country') ?><em>*</em></label>
                        <div class="input-box country-input-box">
                            <?php echo $this->getCountryHtmlSelect() ?>
                        </div>
                    </div>
                </li>
    <?php $userDefinedAttributes = $this->getLayout()->getBlock('customer_form_user_attributes'); ?>
    <?php if ($userDefinedAttributes):?>
        <?php echo $userDefinedAttributes->setEntity($this->getAddress())->setShowContainer(false)->toHtml(); ?>
    <?php endif;?>
                <li class="control">
                    <?php if($this->isDefaultBilling()): ?>
                        <p><strong><?php //echo $this->__('Default Billing Address') ?></strong></p>
                    <?php elseif($this->canSetAsDefaultBilling()): ?>
                        <div class="input-box">
                            <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox no-display" />
                            <label id="custom-primary-billing" class="custom-checkbox" for="primary_billing"><?php echo $this->__('Use as my default billing address') ?></label>
                            <script>
                                jQuery('#primary_billing').on('change', function(){
                                    if(this.checked)
                                    {
                                        jQuery('#custom-primary-billing').addClass('checked');
                                    }
                                    else
                                    {
                                        jQuery('#custom-primary-billing').removeClass('checked');
                                    }
                                });
                            </script>
                        </div>

                    <?php else: ?>
                        <input type="hidden" name="default_billing" value="1" />
                    <?php endif; ?>
                </li>
                <li class="control">
                    <?php if($this->isDefaultShipping()): ?>
                        <p><strong><?php //echo $this->__('Default Shipping Address') ?></strong></p>
                    <?php elseif($this->canSetAsDefaultShipping()): ?>
                        <div class="input-box">
                            <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox no-display" />
                            <label id="custom-primary-shipping" class="custom-checkbox" for="primary_shipping"><?php echo $this->__('Use as my default shipping address') ?></label>
                            <script>
                                jQuery('#primary_shipping').on('change', function(){
                                    if(this.checked)
                                    {
                                        jQuery('#custom-primary-shipping').addClass('checked');
                                    }
                                    else
                                    {
                                        jQuery('#custom-primary-shipping').removeClass('checked');
                                    }
                                });
                            </script>
                        </div>
                    <?php else: ?>
                        <input type="hidden" name="default_shipping" value="1" />
                    <?php endif; ?>
                </li>
            </ul>
            <div class="buttons-set form-buttons">
                <button type="submit" class="button" title="<?php echo $this->__('Save') ?>"><span><span><?php echo $this->__('Save') ?></span></span></button>
            </div>
         </div>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    jQuery('#country').customSelect();
    //rewrite VarienForm.prototype.setMarkDisplay method for custom Select Refreshing
    RegionUpdater.prototype.setMarkDisplay_orig = RegionUpdater.prototype.setMarkDisplay;
    RegionUpdater.prototype.setMarkDisplay = function(elem, display){
        RegionUpdater.prototype.setMarkDisplay_orig.apply(this, arguments);
        //alert(element.config.code);
        console.log(display);
        jQuery(elem).customSelectRefresh();
        if(display){
            jQuery('#custom_region_id').show();
            jQuery('#custom-required-region').show();
        } else{
            jQuery('#custom_region_id').hide();
            jQuery('#custom-required-region').hide();
        }
    };

    var dataForm = new VarienForm('form-validate', true);
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');

//]]>
</script>
