<?php /* @var $this Mage_Directory_Block_Currency */ ?>
<?php
	/* Currency drop down */
?>
<?php if($this->getCurrencyCount() > 1): ?>
    <div class="mobile-currency-switcher">
        <div class="caption"><?php echo $this->__('Currency') ?></div>
        <ul>
            <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
                <li class="currency-switch-item<?php if($_code == $this->getCurrentCurrencyCode()): ?> active<?php endif; ?>" data-value="<?php echo $this->getSwitchCurrencyUrl($_code)?>">
                    <span><?php echo Mage::app()->getLocale()->currency($_code)->getSymbol(); ?></span>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <script>
        jQuery('.currency-switch-item').on('click', function(){
            setLocation(jQuery(this).data('value'));
        });
    </script>
<?php endif; ?>
