<?php
	/* Currency drop down */
?>
<?php if($this->getCurrencyCount() > 1): ?>
<div class="form-language">
    <label for="custom-currency-selector"><?php echo $this->__('Currency') ?></label>
    <select onchange="window.location.href=this.value" name="custom-currency-selector" id="custom-currency-selector">
        <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
        
        <option value="<?php echo $this->getSwitchCurrencyUrl($_code)?>"
            <?php if($_code == $this->getCurrentCurrencyCode()): ?>
                selected="selected"
            <?php endif; ?>>
            <?php echo Mage::app()->getLocale()->currency($_code)->getSymbol(); ?>
        </option>
        <?php endforeach; ?>
    </select>
</div>
<?php endif; ?>
