
<?php
    /* @var $this RonisBT_Cms_Block_Page */
?>

<div class="image-holder image-1">
    <a href="<?php echo $this->escapeHtml($this->getHps2PpX2Image1TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps2PpX2Image1LinkTitle()) ?>">
        <?php $imageSize = getimagesize($this->getImage('hps2_pp_x2_image1')) ?>
        <img <?php echo $imageSize[3] ?> src="<?php echo $this->getImage('hps2_pp_x2_image1') ?>" alt="<?php echo $this->escapeHtml($this->getHps2PpX2Image1LinkTitle()) ?>" />
    </a>
</div>
<div class="image-holder image-2">
    <a href="<?php echo $this->escapeHtml($this->getHps2PpX2Image2TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps2PpX2Image2LinkTitle()) ?>">
        <?php $imageSize = getimagesize($this->getImage('hps2_pp_x2_image2')) ?>
        <img <?php echo $imageSize[3] ?> src="<?php echo $this->getImage('hps2_pp_x2_image2') ?>" alt="<?php echo $this->escapeHtml($this->getHps2PpX2Image2LinkTitle()) ?>" />
    </a>
</div>
<?php if($this->getHps2PpX2TbLinkText() && $this->getHps2PpX2TbTargetUrl()): ?>
    <a class="<?php echo $this->escapeHtml($this->getHps2PpX2TbBgColor()) ?> category-link" href="<?php echo $this->escapeHtml($this->getHps2PpX2TbTargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps2PpX2TbLinkText()) ?>"><span><span><?php echo $this->escapeHtml($this->getHps2PpX2TbLinkText()) ?></span></span></a>
<?php endIf; ?>
<?php if($this->getHps2PpX2AddText()): ?>
    <div class="add-text">
        <p><?php echo $this->escapeHtml($this->getHps2PpX2AddText()) ?></p>
    </div>
<?php endIf; ?>
