
<?php
    /* @var $this RonisBT_Cms_Block_Page */
?>

<div class="image-holder image-1">
    <a href="<?php echo $this->escapeHtml($this->getHps2PpX3Image1TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps2PpX3Image1LinkTitle()) ?>">
        <?php $imageSize = getimagesize($this->getImage('hps2_pp_x3_image1')) ?>
        <img <?php echo $imageSize[3] ?> src="<?php echo $this->getImage('hps2_pp_x3_image1') ?>" alt="<?php echo $this->escapeHtml($this->getHps2PpX3Image1LinkTitle()) ?>" />
    </a>
</div>
<div class="image-holder image-2">
    <a href="<?php echo $this->escapeHtml($this->getHps2PpX3Image2TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps2PpX3Image2LinkTitle()) ?>">
        <?php $imageSize = getimagesize($this->getImage('hps2_pp_x3_image2')) ?>
        <img <?php echo $imageSize[3] ?> src="<?php echo $this->getImage('hps2_pp_x3_image2') ?>" alt="<?php echo $this->escapeHtml($this->getHps2PpX3Image2LinkTitle()) ?>" />
    </a>
</div>
<div class="image-holder image-3">
    <a href="<?php echo $this->escapeHtml($this->getHps2PpX3Image3TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps2PpX3Image3LinkTitle()) ?>">
        <?php $imageSize = getimagesize($this->getImage('hps2_pp_x3_image3')) ?>
        <img <?php echo $imageSize[3] ?> src="<?php echo $this->getImage('hps2_pp_x3_image3') ?>" alt="<?php echo $this->escapeHtml($this->getHps2PpX3Image3LinkTitle()) ?>" />
    </a>
</div>
<?php if($this->getHps2PpX3TbLinkText() && $this->getHps2PpX3TbTargetUrl()): ?>
    <a class="<?php echo $this->escapeHtml($this->getHps2PpX3TbBgColor()) ?> category-link" href="<?php echo $this->escapeHtml($this->getHps2PpX3TbTargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps2PpX3TbLinkText()) ?>"><span><span><?php echo $this->escapeHtml($this->getHps2PpX3TbLinkText()) ?></span></span></a>
<?php endIf; ?>
<?php if($this->getHps2PpX3AddText()): ?>
    <div class="add-text">
        <p><?php echo $this->escapeHtml($this->getHps2PpX3AddText()) ?></p>
    </div>
<?php endIf; ?>
