
<?php
    /* @var $this RonisBT_Cms_Block_Page */
?>

<div class="image-holder image-1">
    <a href="<?php echo $this->escapeHtml($this->getHps2PpX4Image1TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps2PpX4Image1LinkTitle()) ?>">
        <?php $imageSize = getimagesize($this->getImage('hps2_pp_x4_image1')) ?>
        <img <?php echo $imageSize[3] ?> src="<?php echo $this->getImage('hps2_pp_x4_image1') ?>" alt="<?php echo $this->escapeHtml($this->getHps2PpX4Image1LinkTitle()) ?>" />
    </a>
</div>
<div class="image-holder image-2">
    <a href="<?php echo $this->escapeHtml($this->getHps2PpX4Image2TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps2PpX4Image2LinkTitle()) ?>">
        <?php $imageSize = getimagesize($this->getImage('hps2_pp_x4_image2')) ?>
        <img <?php echo $imageSize[3] ?> src="<?php echo $this->getImage('hps2_pp_x4_image2') ?>" alt="<?php echo $this->escapeHtml($this->getHps2PpX4Image2LinkTitle()) ?>" />
    </a>
</div>
<div class="image-holder image-3">
    <a href="<?php echo $this->escapeHtml($this->getHps2PpX4Image3TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps2PpX4Image3LinkTitle()) ?>">
        <?php $imageSize = getimagesize($this->getImage('hps2_pp_x4_image3')) ?>
        <img <?php echo $imageSize[3] ?> src="<?php echo $this->getImage('hps2_pp_x4_image3') ?>" alt="<?php echo $this->escapeHtml($this->getHps2PpX4Image3LinkTitle()) ?>" />
    </a>
</div>
<div class="image-holder image-4">
    <a href="<?php echo $this->escapeHtml($this->getHps2PpX4Image4TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps2PpX4Image4LinkTitle()) ?>">
        <?php $imageSize = getimagesize($this->getImage('hps2_pp_x4_image4')) ?>
        <img <?php echo $imageSize[3] ?> src="<?php echo $this->getImage('hps2_pp_x4_image4') ?>" alt="<?php echo $this->escapeHtml($this->getHps2PpX4Image4LinkTitle()) ?>" />
    </a>
</div>
<?php if($this->getHps2PpX4TbLinkText() && $this->getHps2PpX4TbTargetUrl()): ?>
    <a class="<?php echo $this->escapeHtml($this->getHps2PpX4TbBgColor()) ?> category-link" href="<?php echo $this->escapeHtml($this->getHps2PpX4TbTargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps2PpX4TbLinkText()) ?>"><span><span><?php echo $this->escapeHtml($this->getHps2PpX4TbLinkText()) ?></span></span></a>
<?php endIf; ?>
<?php if($this->getHps2PpX4AddText()): ?>
    <div class="add-text">
        <p><?php echo $this->escapeHtml($this->getHps2PpX4AddText()) ?></p>
    </div>
<?php endIf; ?>
