
<?php
    /* @var $this RonisBT_Cms_Block_Page */
?>

<div class="image-holder image-1">
    <a href="<?php echo $this->escapeHtml($this->getHps2PpX2sImage1TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps2PpX2sImage1LinkTitle()) ?>">
        <?php $imageSize = getimagesize($this->getImage('hps2_pp_x2s_image1')) ?>
        <img <?php echo $imageSize[3] ?> src="<?php echo $this->getImage('hps2_pp_x2s_image1') ?>" alt="<?php echo $this->escapeHtml($this->getHps2PpX2sImage1LinkTitle()) ?>" />
    </a>
</div>
<div class="image-holder image-2">
    <a href="<?php echo $this->escapeHtml($this->getHps2PpX2sImage2TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps2PpX2sImage2LinkTitle()) ?>">
        <?php $imageSize = getimagesize($this->getImage('hps2_pp_x2s_image2')) ?>
        <img <?php echo $imageSize[3] ?> src="<?php echo $this->getImage('hps2_pp_x2s_image2') ?>" alt="<?php echo $this->escapeHtml($this->getHps2PpX2sImage2LinkTitle()) ?>" />
    </a>
</div>
<?php if($this->getHps2PpX2sTbLinkText() && $this->getHps2PpX2sTbTargetUrl()): ?>
    <a class="<?php echo $this->escapeHtml($this->getHps2PpX2TbBgColor()) ?>" href="<?php echo $this->escapeHtml($this->getHps2PpX2sTbTargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps2PpX2sTbLinkText()) ?>"><?php echo $this->escapeHtml($this->getHps2PpX2sTbLinkText()) ?></a>
<?php endIf; ?>
<?php if($this->getHps2PpX2sAddText()): ?>
    <p><?php echo $this->escapeHtml($this->getHps2PpX2sAddText()) ?></p>
<?php endIf; ?>