
<?php
    /* @var $this RonisBT_Cms_Block_Page */
?>

<div class="image-holder image-1">
    <a href="<?php echo $this->escapeHtml($this->getHps2PpX2wImage1TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps2PpX2wImage1LinkTitle()) ?>">
        <?php $imageSize = getimagesize($this->getImage('hps2_pp_x2w_image1')) ?>
        <img <?php echo $imageSize[3] ?> src="<?php echo $this->getImage('hps2_pp_x2w_image1') ?>" alt="<?php echo $this->escapeHtml($this->getHps2PpX2wImage1LinkTitle()) ?>" />
    </a>
</div>
<div class="image-holder image-2">
    <a href="<?php echo $this->escapeHtml($this->getHps2PpX2wImage2TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps2PpX2wImage2LinkTitle()) ?>">
        <?php $imageSize = getimagesize($this->getImage('hps2_pp_x2w_image2')) ?>
        <img <?php echo $imageSize[3] ?> src="<?php echo $this->getImage('hps2_pp_x2w_image2') ?>" alt="<?php echo $this->escapeHtml($this->getHps2PpX2wImage2LinkTitle()) ?>" />
    </a>
</div>
<?php if($this->getHps2PpX2wTb1LinkText() && $this->getHps2PpX2wTb1TargetUrl()): ?>
    <a class="<?php echo $this->escapeHtml($this->getHps2PpX2wTb1BgColor()) ?>" href="<?php echo $this->escapeHtml($this->getHps2PpX2wTb1TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps2PpX2wTb1LinkText()) ?>"><?php echo $this->escapeHtml($this->getHps2PpX2wTb1LinkText()) ?></a>
<?php endIf; ?>
<?php if($this->getHps2PpX2wTb2LinkText() && $this->getHps2PpX2wTb2TargetUrl()): ?>
    <a class="<?php echo $this->escapeHtml($this->getHps2PpX2wTb2BgColor()) ?>" href="<?php echo $this->escapeHtml($this->getHps2PpX2wTb2TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps2PpX2wTb2LinkText()) ?>"><?php echo $this->escapeHtml($this->getHps2PpX2wTb2LinkText()) ?></a>
<?php endIf; ?>
<?php if($this->getHps2PpX2wAddText()): ?>
    <p><?php echo $this->escapeHtml($this->getHps2PpX2wAddText()) ?></p>
<?php endIf; ?>