
<?php
    /* @var $this RonisBT_Cms_Block_Page */
?>

<?php if($videoCode = $this->getHps1Ip4Video()): ?>
    <div class="video-wrapper">
        <iframe id="fvideo" class="fvideo" src="<?php echo Mage::helper('evisu_homepage')->getVideoUrlByCode($videoCode) ?>" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
    </div>
    <a href="javascript:void(null)" class="video-overlay-holder"></a>
<?php endIf; ?>
<?php if($videoCode = $this->getHps1Ip4Image()): ?>
    <div class="image-holder">
        <?php $imageSize = getimagesize($this->getImage('hps1_ip4_image')) ?>
        <img <?php echo $imageSize[3] ?> src="<?php echo $this->getImage('hps1_ip4_image') ?>" alt="" />
    </div>
<?php endIf; ?>
<?php $linkText = $this->getHps1Ip4LinkText(); if($linkText && $this->getHps1Ip4TargetUrl()): ?>
    <a href="<?php echo $this->escapeHtml($this->getHps1Ip4TargetUrl()) ?>" class="text-link" title="<?php echo $this->escapeHtml($this->getHps1Ip4LinkText()) ?>"><span class="text-link-holder"><span class="text-link-wrapper"><?php echo $this->escapeHtml($this->getHps1Ip4LinkText()) ?></span></span></a>
<?php elseif(!$linkText && $this->getHps1Ip4TargetUrl()): ?>
    <a href="<?php echo $this->escapeHtml($this->getHps1Ip4TargetUrl()) ?>"></a>
<?php endIf; ?>
