
<?php
    /* @var $this RonisBT_Cms_Block_Page */
?>

<?php if($videoCode = $this->getHps1Ip7Video()): ?>
    <iframe class="fvideo" src="<?php echo Mage::helper('evisu_homepage')->getVideoUrlByCode($videoCode) ?>" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
<?php else: ?>
    <div class="image-holder">
        <?php $imageSize = getimagesize($this->getImage('hps1_ip7_image')) ?>
        <img <?php echo $imageSize[3] ?> src="<?php echo $this->getImage('hps1_ip7_image') ?>" alt="" />
    </div>
<?php endIf; ?>
<?php if($this->getHps1Ip7LinkText() && $this->getHps1Ip7TargetUrl()): ?>
    <a href="<?php echo $this->escapeHtml($this->getHps1Ip7TargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps1Ip7LinkText()) ?>"><?php echo $this->escapeHtml($this->getHps1Ip7LinkText()) ?></a>
<?php endIf; ?>