
<?php
    /* @var $this RonisBT_Cms_Block_Page */
?>
<?php if($videoCode = $this->getHps1Ip1Video()): ?>
    <iframe class="fvideo" src="<?php echo Mage::helper('evisu_homepage')->getVideoUrlByCode($videoCode) ?>" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
<?php else: ?>
    <div class="image-holder">
        <?php $imageSize = getimagesize($this->getImage('hps1_ip1_image')) ?>
        <img <?php echo $imageSize[3] ?> src="<?php echo $this->getImage('hps1_ip1_image') ?>" alt="" />
    </div>
<?php endIf; ?>
<?php $linkText = $this->getHps1Ip1LinkText(); if($linkText && $this->getHps1Ip1TargetUrl()): ?>
    <a href="<?php echo $this->escapeHtml($this->getHps1Ip1TargetUrl()) ?>" class="text-link" title="<?php echo $this->escapeHtml($this->getHps1Ip1LinkText()) ?>"><span class="text-link-holder"><span class="text-link-wrapper"><?php echo $this->escapeHtml($this->getHps1Ip1LinkText()) ?></span></span></a>
<?php elseif(!$linkText && $this->getHps1Ip1TargetUrl()): ?>
    <a href="<?php echo $this->escapeHtml($this->getHps1Ip1TargetUrl()) ?>"></a>
<?php endIf; ?>