
<?php
    /* @var $this RonisBT_Cms_Block_Page */
?>

<?php if($videoCode = $this->getHps1Ip7Video()): ?>
    <div class="video-wrapper">
        <iframe class="fvideo" src="<?php echo Mage::helper('evisu_homepage')->getVideoUrlByCode($videoCode) ?>" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
    </div>
    <a href="#" class="video-overlay-holder"></a>
<?php endIf; ?>
<?php if($videoCode = $this->getHps1Ip7Image()): ?>
    <div class="image-holder">
        <?php $imageSize = getimagesize($this->getImage('hps1_ip7_image')) ?>
        <img <?php echo $imageSize[3] ?> src="<?php echo $this->getImage('hps1_ip7_image') ?>" alt="" />
    </div>
<?php endIf; ?>
<?php $linkText = $this->getHps1Ip7LinkText(); if($linkText && $this->getHps1Ip7TargetUrl()): ?>
    <a href="<?php echo $this->escapeHtml($this->getHps1Ip7TargetUrl()) ?>" class="text-link" title="<?php echo $this->escapeHtml($this->getHps1Ip7LinkText()) ?>"><span class="text-link-holder"><span class="text-link-wrapper"><?php echo $this->escapeHtml($this->getHps1Ip7LinkText()) ?></span></span></a>
<?php elseif(!$linkText && $this->getHps1Ip7TargetUrl()): ?>
    <a href="<?php echo $this->escapeHtml($this->getHps1Ip7TargetUrl()) ?>"></a>
<?php endIf; ?>
