
<?php
    /* @var $this RonisBT_Cms_Block_Page */
?>

<h2><?php echo $this->escapeHtml($this->getHps1TextBlockHeader()) ?></h2>
<div class="section-description"><p><?php echo nl2br($this->escapeHtml($this->getHps1TextBlockText())) ?></p></div>
<?php if($this->getHps1TextBlockLinkText() && $this->getHps1TextBlockTargetUrl()): ?>
    <div class="section-main-link"><a href="<?php echo $this->escapeHtml($this->getHps1TextBlockTargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps1TextBlockLinkText()) ?>"><?php echo $this->escapeHtml($this->getHps1TextBlockLinkText()) ?></a></div>
<?php endIf; ?>
