
<?php
    /* @var $this RonisBT_Cms_Block_Page */
?>

<?php if($videoCode = $this->getHps3IprVideo()): ?>
    <iframe class="fvideo" src="<?php echo Mage::helper('evisu_homepage')->getVideoUrlByCode($videoCode) ?>" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
<?php else: ?>
    <div class="image-holder">
        <?php $imageSize = getimagesize($this->getImage('hps3_ipr_image')) ?>
        <img <?php echo $imageSize[3] ?> src="<?php echo $this->getImage('hps3_ipr_image') ?>" alt="" />
    </div>
<?php endIf; ?>
<h2><?php echo $this->escapeHtml($this->getHps3IprHeader()) ?></h2>
<h3><?php echo $this->escapeHtml($this->getHps3IprTitle()) ?></h3>
<p><?php echo nl2br($this->escapeHtml($this->getHps3IprText())) ?></p>
<a href="<?php echo $this->escapeHtml($this->getHps3IprTargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps3IprLinkText()) ?>"><?php echo $this->escapeHtml($this->getHps3IprLinkText()) ?></a>