
<?php
    /* @var $this RonisBT_Cms_Block_Page */
?>

<?php if($videoCode = $this->getHps3IplVideo()): ?>
    <iframe class="fvideo" src="<?php echo Mage::helper('evisu_homepage')->getVideoUrlByCode($videoCode) ?>" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
<?php else: ?>
    <div class="image-holder">
        <?php $imageSize = getimagesize($this->getImage('hps3_ipl_image')) ?>
        <img <?php echo $imageSize[3] ?> src="<?php echo $this->getImage('hps3_ipl_image') ?>" alt="" />
    </div>
<?php endIf; ?>
<h2><?php echo $this->escapeHtml($this->getHps3IplHeader()) ?></h2>
<h3><?php echo $this->escapeHtml($this->getHps3IplTitle()) ?></h3>
<p><?php echo nl2br($this->escapeHtml($this->getHps3IplText())) ?></p>
<a href="<?php echo $this->escapeHtml($this->getHps3IplTargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps3IplLinkText()) ?>"><?php echo $this->escapeHtml($this->getHps3IplLinkText()) ?></a>