
<?php
    /* @var $this RonisBT_Cms_Block_Page */
?>
<a class="<?php echo $this->escapeHtml($this->getHps3SbBgColor()) ?>" href="<?php echo $this->escapeHtml($this->getHps3SbTargetUrl()) ?>" title="<?php echo $this->escapeHtml($this->getHps3SbLinkText()) ?>"><?php echo $this->escapeHtml($this->getHps3SbLinkText()) ?></a>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('social_links_block')->toHtml() ?>

