<?php /* @var $this Fishpig_Wordpress_Block_Post_List */ ?>
<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $tweets = Mage::getSingleton('latesttweet/tweets') ?>
<?php $helper = Mage::helper('evisu_blog')?>
<?php $posts = $this->getPosts() ?>
<?php if (count($posts) > 0): ?>
	<div class="post-list">
		<ul id="post-list">
			<?php $i = 0; foreach($posts as $post): ?>
                <?php if($helper->showTwitter($i)): ?>
                    <?php if($tweet = $tweets->getTweet()): ?>
                        <li class="item tweet-<?php echo $tweets->getCurrentTweetNumber() ?>">
                            <div class="twit">
                                <div class="twitter-logo"></div>
                                <div class="twit-date"><?php echo $tweet['date'] ?></div>
                                <div class="twit-text"><?php echo $tweet['text'] ?></div>
                            </div>
                        </li>
                    <?php endIf; ?>
                <?php endIf; ?>
				<li class="item<?php if ($post->isSticky()): ?> featured<?php endif; ?>">
                    <?php $post->setPosition($i) ?>
					<?php echo $this->getPostRenderer($post)->toHtml() ?>
				</li>
			<?php $i++; endforeach; ?>
		</ul>
		<script type="text/javascript">decorateList($('post-list'));</script>
		<?php echo $this->getPagerHtml() ?>
        <?php echo $this->getChildHtml('instagram') ?>
	</div>
<?php endif; ?>