<?php /* @var $this Mage_Customer_Block_Account_Dashboard_Address */ ?>
<div class="billing-address">
    <div class="caption"><?php echo $this->__('Default Billing Address') ?></div>
    <address>
        <?php echo $this->getPrimaryBillingAddressHtml() ?>
    </address>
</div>
<div class="shipping-address">
    <div class="caption"><?php echo $this->__('Default Shipping Address') ?></div>
    <address>
        <?php echo $this->getPrimaryShippingAddressHtml() ?>
    </address>
</div>
<div class="links">
    <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit') ?></a>
    <a href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage / Add New') ?></a>
</div>

<?php /*
<div class="col-2">
    <div class="info-box">
        <h3 class="box-title"><?php echo $this->__('Default Shipping Address') ?> <span class="separator">|</span> <a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a></h3>
        <address class="box-content">
            <?php echo $this->getPrimaryShippingAddressHtml() ?>
        </address>
    </div>
</div>
*/ ?>
